USER = "INSERT USERNAME"
PASSWORD = "INSERT PASSWORD"
HOST_PORT = "INSERT HOST:PORT"
DB = "INSERT DATABASE NAME"

SQLALCHEMY_DATABASE_URL = "mysql+pymysql://{}:{}@{}/{}".format(USER, PASSWORD, HOST_PORT, DB)